version: '3'

services:
  ui:
    image: wirelos/infranodus
    build: .
    env_file: .env
    ports:
      - 3000:3000
  db:
    image: neo4j:3.5.8
    env_file: bootstrap.env
    environment:
      - UID=1000
      - GUID=1000
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_trigger_enabled=true
    volumes:
      - $HOME/infranodus/conf:/var/lib/neo4j/conf
      - $HOME/infranodus/data:/data
      - $PWD/import:/var/lib/neo4j/import
      - $PWD/deps/plugins:/var/lib/neo4j/plugins
    ports:
      - 7474:7474 
      - 7687:7687