version: '3'

services:
  infranodus-ui:
    restart: unless-stopped
    image: wirelos/infranodus
    build: .
    env_file: default.env
    #ports:
    #  - 3000:3000
    labels:
      - flame.type=application # "app" works too
      - flame.name=Infranodus
      - flame.url=https://infranodus.dcentral.systems
      - flame.icon=network 
  infranodus-db:
    image: wirelos/infranodus-db:3.5.8
    build: ./db/build
    restart: unless-stopped
    environment:
      - UID=1000
      - GUID=1000
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_trigger_enabled=true
    volumes:
      - ./data/conf:/var/lib/neo4j/conf
      - ./data/db:/data
      #- $PWD/vagrant:/var/lib/neo4j/install
      #- $DATA_PATH/plugins:/var/lib/neo4j/plugins
    #ports:
    #  - 7474:7474 
    #  - 7687:7687
networks:
  default:
    name: grid
    external: true
